var profile = "https://avatars.githubusercontent.com/u/86506519?v=4";

List<Map<String, dynamic>> pets = [

  {
    "image": "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Cheero",
    "location": "Siem Reap, Cambodia",
    "is_favorited": true,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5, 
    "id": "pid001",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffC1B7B1",

  },
  {
    "image": "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Bossy",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5, 
    "id": "pid002",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffD7BF9D",
  },
  {
    "image": "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Maxi",
    "location": "Battambang, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5, 
    "id": "pid003",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffB1D1FF",
  },
  {
    "image": "https://images.unsplash.com/photo-1588269845464-8993565cac3a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Coca",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5, 
    "id": "pid004",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffC1B7B1",
  },
  {
    "image": "https://images.unsplash.com/photo-1556227702-d1e4e7b5c232?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Lazoo",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": true,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5, 
    "id": "pid005",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffD7BF9D",
  },
  {
    "image": "https://images.unsplash.com/photo-1598875184988-5e67b1a874b8?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Meido",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5, 
    "id": "pid006",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffB1D1FF",
  },
  {
    "image": "https://images.unsplash.com/photo-1587764379873-97837921fd44?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Koko",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5, 
    "id": "pid007",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffC1B7B1",
  },
  {
    "image": "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Roka",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5, 
    "id": "pid008",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffB1D1FF",
  },
  {
    "image": "https://images.unsplash.com/photo-1583511655826-05700d52f4d9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "kheero",
    "location": "Siem Reap, Cambodia",
    "is_favorited": true,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid009",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffC1B7B1",
  },
  {
    "image": "https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Lossy",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid010",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffB1D1FF",
  },
  {
    "image": "https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Maxi",
    "location": "Battambang, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid011",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffC1B7B1",
  },
  {
    "image": "https://images.unsplash.com/photo-1588269845464-8993565cac3a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Coca",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid012",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffB1D1FF",
  },
  {
    "image": "https://images.unsplash.com/photo-1556227702-d1e4e7b5c232?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Lazoo",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": true,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid013",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffC1B7B1",
  },
  {
    "image": "https://images.unsplash.com/photo-1598875184988-5e67b1a874b8?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Meido",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid014",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffB1D1FF",
  },
  {
    "image": "https://images.unsplash.com/photo-1587764379873-97837921fd44?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Koko",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid015",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffB1D1FF",
  },
  {
    "image": "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8Zm9vZHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60",
    "name": "Roka",
    "location": "Phnom Penh, Cambodia",
    "is_favorited": false,
    "description": "Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "rate": 4.5,
    "id": "pid016",
    "price": "\$1,250",
    "owner_name": "Sangvaleap",
    "owner_photo": profile,
    "sex": "Male",
    "age": "5 Months",
    "color": "0xffB1D1FF",
  },
];

